services:
    sonata.admin.post:
        class: AppBundle\Admin\JamJarAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "JamJar" }
        arguments:
            - ~
            - AppBundle\Entity\JamJar
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle]]